//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Dorgem.rc
//
#define IDC_MOVE_DOWN                   3
#define IDM_ABOUTBOX                    0x0010
#define IDC_OPTIONS                     17
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DORGEM_DIALOG               102
#define IDS_FTPMSG1                     103
#define IDS_FTPMSG2                     104
#define IDS_FTPMSG3                     105
#define IDS_FTPMSG4                     106
#define IDS_FTPMSG5                     107
#define IDS_FTPMSG6                     108
#define IDR_MAINFRAME                   128
#define IDD_PREVIEW                     129
#define IDD_CAPTION_SETTINGS            130
#define IDD_STORE_SETTINGS              132
#define IDD_STORE_FILE                  133
#define IDD_STORE_FTP                   134
#define IDD_STORE_SELECT                135
#define IDC_LINK_CURSOR                 136
#define IDD_CAPTION_BMP                 136
#define IDD_CAPTION_TXT                 137
#define IDR_TRAYPOPUP                   138
#define IDD_CAPTION_SELECT              139
#define IDD_OPTIONS_GENERAL             140
#define IDD_OPTIONS_AVI                 141
#define IDD_OPTIONS_WEB_SERVER          142
#define IDC_COLOR_SELECT                143
#define IDD_STORE_PROGRAM               144
#define IDD_CAPTION_POS                 145
#define IDD_STORE_HTTP                  146
#define IDD_COLOR_SELECT                147
#define IDC_PREVIEW                     1000
#define IDC_VERSION_STR                 1001
#define IDC_CAPTION_SETTINGS            1002
#define IDC_COPYRIGHT_STR               1003
#define IDC_RELEASE_STR                 1004
#define IDC_DEVICES                     1005
#define IDC_CAPTURE_NOW                 1006
#define IDC_DEV_SOURCE                  1007
#define IDC_DEV_FORMAT                  1008
#define IDC_DEV_DISPLAY                 1009
#define IDC_CHANGE                      1010
#define IDC_DELETE                      1011
#define IDC_USE_AVI                     1011
#define IDC_USE_CAPTION                 1012
#define IDC_STORE_SETTINGS              1014
#define IDC_CAPTION                     1015
#define IDC_STORE                       1018
#define IDC_ADD                         1019
#define IDC_BMP_TYPE                    1020
#define IDC_CAP_LANG                    1021
#define IDC_COMPRESS                    1022
#define IDC_COMPRESS_SPIN               1023
#define IDC_TRANSPARENT                 1024
#define IDC_SHADOW                      1025
#define IDC_BACK_COLOR                  1026
#define IDC_FORE_COLOR                  1027
#define IDC_FONT                        1028
#define IDC_BITMAP                      1029
#define IDC_BROWSE                      1030
#define IDC_NAME                        1031
#define IDC_INTERVAL                    1032
#define IDC_FILE                        1033
#define IDC_FPS                         1034
#define IDC_SEL_FILE                    1035
#define IDC_SEL_FTP                     1036
#define IDC_RAS_CONN                    1037
#define IDC_SEL_PROGRAM                 1037
#define IDC_SEL_HTTP                    1038
#define IDC_USER                        1039
#define IDC_PASSWORD                    1041
#define IDC_HOST                        1043
#define IDC_USE_RAS                     1045
#define IDC_ENABLE                      1046
#define IDC_RESET_TIME                  1047
#define IDC_KEEP_OPEN                   1048
#define IDC_CREATE_DIRS                 1048
#define IDC_SEL_BMP                     1049
#define IDC_PASSIVE_FTP                 1049
#define IDC_SEL_TXT                     1050
#define IDC_MOVE_UP                     1051
#define IDC_URL                         1053
#define IDC_CHECK_VERSION               1054
#define IDC_TRAY_ICON                   1055
#define IDC_MOTION_DETECTION            1056
#define IDC_FPS_SPIN                    1057
#define IDC_RECONNECT                   1057
#define IDC_SHOW_MSGBOX                 1058
#define IDC_USE_SERVER                  1060
#define IDC_RECONNECT_TIME              1061
#define IDC_MINUTES                     1062
#define IDC_PORT                        1063
#define IDC_COMMAND                     1064
#define IDC_SERVER_TYPE                 1065
#define IDC_REFRESH                     1066
#define IDC_LOG_FILE                    1068
#define IDC_INTERVAL_TYPE               1069
#define IDC_RELATIVE                    1070
#define IDC_ABSOLUTE                    1071
#define IDC_POS_VER_ABS                 1072
#define IDC_POS_HOR_ABS                 1073
#define IDC_POS_VER_REL                 1074
#define IDC_POS_HOR_REL                 1075
#define IDC_POSITION                    1076
#define IDC_TRANS_SELECT                1077
#define IDC_LENGTH                      1080
#define IDC_SECURE                      1081
#define IDC_CAP_CUST                    1084
#define IDC_PICTURE                     1086
#define IDC_CAPTURE                     1087
#define IDC_STATUS                      1088
#define IDC_CUR_TRANS                   1089
#define IDC_REFRESH_TYPE                1090
#define IDC_RESTORE                     32771
#define IDS_PRODUCT_NAME                65070
#define IDS_PRODUCT_VERSION             65071
#define IDS_PRODUCT_COPYRIGHT           65072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
